name: React CI

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

  repository_dispatch:
    types: [workflow]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: actions/setup-python@v2

      - name: "Deploy"
        run: |
          pip install fandogh_cli --upgrade
          COLLECT_ERROR=True fandogh login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
          fandogh namespace active --name mjavad
          fandogh source run