name: React CI

on:
  workflow_dispatch:

  repository_dispatch:
    types: [workflow]

env:
  PYTHON_VERSION: 3.9

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      
  py-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: "Deploy"
        run: |
          COLLECT_ERROR=True pip install fandogh_cli --upgrade
          fandogh login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
          fandogh namespace active --name mjavad
          fandogh source run
